### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by Charsles** [yretenai/LibreFios#1]
Hey there, Yretenai, how are you? i know this is not the place to do this but i didn't found any socials of you so i could send you a private DM but would you mind hit me on discord so we could talk? i'm a modder and i decided to start making Marvel Ultimate Alliance 3 Mods, i knew that this game had no tools at all and while looking for a plugin to export the .ZL_ files, i found this Thread on Xentax and TheVGResource that had you name on it along with this person called Joschka. if i'm correct, you are the done that did the QuickBMS plugin to export the files from the .ZL_ format, right? since i saw this, i've been trying to find a way to ask you if you could do an repacker for the .Bin files that comes out from the .ZL_, but sadly i didn't knew how i could reach you, so i asked in a lot forums if someone could make and to my surprise, someone actually did a repack, not only a repacker but a repeacker tool, can you belive it? now that we have this tool, we can mod retextures in the game (i will be putting the photos in here so you can see)
![imagem_2024-09-05_081246215](https://github.com/user-attachments/assets/efd31040-eadd-411f-beeb-196910b3dbef)

talking about the most important and fun part, the models... i found out this guy on Twitter that managed to get the models from the game and so i joint his discord and he told me that there were a tool to export the models, and again it was one of your tools, the Cethleann one. he tought me how to use the tool to export the model and i decided to make some tests using Dead or Alive 6 G1M tools to see if i could reach more far on making mods and i actually did it! DOA6 plugins is funcional with this game, i even managed to open the file on blender using the g1m tool from this person called vagonumero13. i can open the file and export using blender
![image](https://github.com/user-attachments/assets/ed4a4bbb-c0d3-47f0-bcd9-7943befefd0f)

Wich means that we can mod the models of the game, but since we don't have a g1m tool to convert the model to .bin again, is it asking for much for you to make that "Cethleann.Unbundler.exe" a repacker for the g1m files to .bin? i know that this is inconvenient but since we have a tool to repack the .bin to .ZL_, we are one step closer to make model mods are thing too, and trust me, i would never do this if didn't want to mod this game THAT MUCH. i really like this game and nobody did mods for it before because we didn't had any tools and i really wanted to change that. i've managed to make some sound on Reddit and on MUA servers by showing that recolors are now a thing and people is exited. again, sorry for the inconvenience and commenting on a post that it's not even related anything from this game but i really didn't knew how to reach you and the Cethleann topic is closed so the only way that i found out to reach you was going to a recent post. you can delete this post as soon as you see this and reply me on discord if you want! wich is Chars_. it's okey if you don't want to make the tool too, i know that it's a lot of work and time that you need to invest! thank you in advance 🦋

**Comment by neptuwunium** [comment]
Sorry I've ceased development of Cethleann and will not be returning to it due to how much stress that engine has given me. The source code remains freely open and available, if someone was skilled enough to make a tool to re-pack ZL files they probably can find the code that parses those .bin files. Regrettably, the Cethleann code is also of not good quality (part of the reason I ceased development) and I can only apologize for that.
